name: create-release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: use node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: build client
      working-directory: client
      run: npm ci && npm run build

    - name: build SDF
      working-directory: SDF
      run: npm ci && npm run build
